source: "wiktionary"

commands:
  help: ["h", "help"]

  quit: ["q", "exit", "quit"]

  search: ["s", "search"]

  flip:
    cmds: ["f", "flip"]
    randomize: ["r", "random"]
    next: ["n", "j", ""]
    prev: ["p", "k", "."]
